Repository so-sim/server, pull requests merged in 2023-06, with the labels that each got.

#19 Refactor : 로그인 수정, Response 명세 일치 작업
  src/main/java/com/sosim/server/common/response/ResponseCode.java
  src/main/java/com/sosim/server/oauth/OAuthController.java
  src/main/java/com/sosim/server/oauth/OAuthService.java
  src/main/java/com/sosim/server/oauth/OAuthUserFactory.java
  src/main/java/com/sosim/server/oauth/dto/response/LoginResponse.java
Labels: ♻️refactor

#21 [Refactor] User
  src/main/java/com/sosim/server/participant/Participant.java
  src/main/java/com/sosim/server/participant/ParticipantRepository.java
  src/main/java/com/sosim/server/user/User.java
  src/main/java/com/sosim/server/user/UserController.java
  src/main/java/com/sosim/server/user/UserService.java
  src/main/java/com/sosim/server/user/dto/request/WithdrawRequest.java
  src/test/java/com/sosim/server/user/UserControllerTest.java
Labels: ♻️refactor

#25 Feat : CORS 세팅 추가
  src/main/java/com/sosim/server/config/WebMvcConfig.java
Labels: ✨feat

#32 Fix: delete된 event 조회에서 제거
  src/main/java/com/sosim/server/event/Event.java
  src/main/java/com/sosim/server/event/EventController.java
  src/main/java/com/sosim/server/event/EventRepository.java
  src/main/java/com/sosim/server/event/EventService.java
Labels: bug
