Repository so-sim/server, pull requests merged in 2023-02, with the labels that each got.

#4 Feature : Create Config
  server/src/main/java/com/sosim/server/config/SecurityConfig.java
  server/src/test/java/com/sosim/server/config/SecurityConfigTest.java
Labels: Setting

#5 docs : create issue template
  server/.github/ISSUE_TEMPLATE/docs.md
  server/.github/ISSUE_TEMPLATE/etc.md
  server/.github/ISSUE_TEMPLATE/feature_request.md
  server/.github/ISSUE_TEMPLATE/refactoring.md
Labels: documentation

#6 etc : 디렉터리 수정
  .github/ISSUE_TEMPLATE/docs.md
  .github/ISSUE_TEMPLATE/etc.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/refactoring.md
Labels: Setting

#11 chore : 기초 디렉터리 및 파일 셋팅#1
  server/src/main/java/com/sosim/server/config/SecurityConfig.java
  server/src/main/java/com/sosim/server/jwt/JwtFactory.java
  server/src/main/java/com/sosim/server/jwt/JwtProvider.java
  server/src/main/java/com/sosim/server/jwt/JwtRepository.java
  server/src/main/java/com/sosim/server/jwt/JwtService.java
  server/src/main/java/com/sosim/server/jwt/RefreshToken.java
  server/src/main/java/com/sosim/server/jwt/util/JwtProperties.java
  server/src/main/java/com/sosim/server/security/authentication/AuthenticationFilter.java
  server/src/main/java/com/sosim/server/security/authorization/AuthorizationFilter.java
  server/src/main/java/com/sosim/server/user/User.java
  server/src/main/java/com/sosim/server/user/UserRepository.java
  server/src/main/java/com/sosim/server/user/UserService.java
  server/src/test/java/com/sosim/server/config/SecurityConfigTest.java
Labels: Setting

#12 feature : 시큐리티 컨텍스트 관련 객체 생성
  server/src/main/java/com/sosim/server/jwt/JwtServiceImpl.java
  server/src/main/java/com/sosim/server/security/AuthUser.java
  server/src/main/java/com/sosim/server/user/UserController.java
Labels: 기능 구현 필요, 기능 구현 완료

#13 feature : create security config
  server/src/main/java/com/sosim/server/config/SecurityConfig.java
Labels: 기능 구현 필요, Setting

#16 fix : 디렉터리 수정 및 ci pipeline 작성
  .github/workflows/cicd.yml
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/sosim/server/ServerApplication.java
  src/main/java/com/sosim/server/config/SecurityConfig.java
  src/main/java/com/sosim/server/jwt/JwtFactory.java
  src/main/java/com/sosim/server/jwt/JwtProvider.java
  src/main/java/com/sosim/server/jwt/JwtRepository.java
  src/main/java/com/sosim/server/jwt/JwtService.java
  src/main/java/com/sosim/server/jwt/JwtServiceImpl.java
  src/main/java/com/sosim/server/jwt/RefreshToken.java
  src/main/java/com/sosim/server/jwt/util/JwtProperties.java
  src/main/java/com/sosim/server/oauth/Oauth2Util.java
  src/main/java/com/sosim/server/oauth/dto/OauthProfileDto.java
  src/main/java/com/sosim/server/oauth/dto/OauthTokenDto.java
  src/main/java/com/sosim/server/security/AuthUser.java
  src/main/java/com/sosim/server/security/authentication/AuthenticationFilter.java
  src/main/java/com/sosim/server/security/authorization/AuthorizationFilter.java
  src/main/java/com/sosim/server/user/User.java
  src/main/java/com/sosim/server/user/UserController.java
  src/main/java/com/sosim/server/user/UserRepository.java
  src/main/java/com/sosim/server/user/UserService.java
  src/main/resources/application.properties
  src/test/java/com/sosim/server/ServerApplicationTests.java
  src/test/java/com/sosim/server/config/SecurityConfigTest.java
Labels: documentation, 기능 구현 완료

#21 refactor : Security 제공 OAuth2 Client
  src/main/java/com/sosim/server/config/SecurityConfig.java
  src/main/java/com/sosim/server/oauth/CustomOAuth2UserService.java
  src/main/java/com/sosim/server/oauth/OAuth2UserInfoFactory.java
  src/main/java/com/sosim/server/oauth/Oauth2Util.java
  src/main/java/com/sosim/server/oauth/dto/GoogleOAuth2UserInfoDto.java
  src/main/java/com/sosim/server/oauth/dto/KakaoOAuth2UserInfoDto.java
  src/main/java/com/sosim/server/oauth/dto/OAuth2UserInfoDto.java
  src/main/java/com/sosim/server/oauth/dto/OauthProfileDto.java
  src/main/java/com/sosim/server/oauth/dto/OauthTokenDto.java
  src/main/java/com/sosim/server/security/AuthUser.java
  src/main/resources/application-oauth.yml
Labels: 기능 구현 완료
